server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: repo-manager-backend
  
github:
  api:
    base-url: https://api.github.com
    
logging:
  level:
    com.repomanager: DEBUG
    org.springframework.web: INFO